export const data = {
    data: {
        id: 1080,
        name: "Icecream",
        code: "has-children",
        sku: "",
        slug: "icecream-sandwitch",
        description:
            "lorem ipsum dolor sit amet, consectetur adip id elit lorem ipsum dolor sit amet, consectetur adip id elit lorem ipsum dolor sit amet, consectetur adip id elit lorem ipsum dolor sit amet, consectetur adip id elit lorem ipsum dolor sit amet, consectetur adip id elit lorem ipsum dolor sit amet, consectetur adip id elit lorem ipsum dolor sit amet, consectetur adip id elit lorem ipsum dolor sit amet, consectetur adip id elit lorem ipsum dolor sit amet, consectetur adip id elit elit Lorem, ipsum dolor sit amet consectetur adipisicing elit. Assumenda ullam unde, error vel, consequuntur animi nobis deserunt voluptatibus, dolore numquam quo? Quidem quibusdam nulla molestiae voluptatem, voluptates excepturi cum adipisci? Lorem ipsum lorem ipsum dolor sit amet, consectetur adip id elit lorem ipsum dolor sit amet, consectetur adip id elit lorem ipsum dolor sit amet, consectetur adip id elit lorem ipsum dolor sit amet, consectetur adip id elit lorem ipsum dolor sit amet, consectetur adip id elit lorem ipsum dolor sit amet, consectetur adip id elit lorem ipsum dolor sit amet, consectetur adip id elit lorem ipsum dolor sit amet, consectetur adip id elit lorem ipsum dolor sit amet, consectetur adip id elit elit Lorem, ipsum dolor sit amet consectetur adipisicing elit. Assumenda ullam unde, error vel, consequuntur animi nobis deserunt voluptatibus, dolore numquam quo? Quidem quibusdam nulla molestiae voluptatem, voluptates excepturi cum adipisci? Lorem ipsum",
        summary: " Demo thing looooo ",
        parent_id: null,
        categories: [null],
        brand: null,
        brand_id: null,
        shop_id: null,
        vendor_id: 1,
        regular_price: "$87.000",
        sale_price: "$73.000",
        available_from: "30-11--0001",
        available_to: "30-11--0001",
        taxable: false,
        tax_class_ids: [2, 3, 5],
        total_sales: null,
        featured: "2022-06-21 13:07:38",
        virtual: false,
        downloadable: true,
        downloads: {
            file1: {
                name: "idm.zip",
                url: "multivendor.com/uploads/idm.zip",
                thumbnail: "multivendor.com/image/thumb.jpg",
            },
            file2: {
                name: "photoshop.zip",
                url: "multivendor.com/uploads/ps.zip",
                thumbnail: "multivendor.com/image/thumb.jpg",
            },
        },
        download_limit: {
            file1: 40,
            file2: 120,
        },
        status: "Published",
        total_downloads: null,
        manege_stocks: true,
        stock_quantity: 200,
        backorders: true,
        critical_stock_quantity: 20,
        weight: 2.5,
        dimensions: {
            height: 10,
            width: 20,
            length: 10,
        },
        shipping_status: true,
        shipping_required: true,
        is_shipping_taxable: true,
        shipping_class_ids: [1, 4, 5],
        reviews_allowed: false,
        related_ids: [1022, 1043],
        upsell_ids: [1022, 1043],
        cross_sell_ids: [1022, 1043],
        purchase_note: "This is a purchase note",
        images: [
            "http://multivendor.com/images/image1.jpg",
            "http://multivendor.com/images/image2.jpg",
            "http://multivendor.com/images/dsafads.jpg",
            "http://multivendor.com/images/fetrea.jpg",
        ],
        meta: {
            cash_on_delivery: true,
        },
        tags: ["abc", "def"],
        warranty_type: "Brand Warranty",
        warranty_period: "1 Year",
        warranty_policy: "No warranty. Go to hell.",
        review_count: 0,
        review_average: null,
        total_wish: 0,
        created_at: "22-06-2022 02:33 PM",
        updated_at: "22-06-2022 03:11 PM",
        image: "http://multivendor.testapp/public/dist/img/default_product.jpg",
        attributes: {
            flavor: {
                name: "Flavor",
                position: 0,
                key: "flavor",
                value: ["Vanilla", "Chocolate", "Banana"],
                visibility: "1",
                attribute_id: "",
                type: "dropdown",
            },
            color: {
                name: "Color",
                position: 1,
                key: "color",
                value: [25, 26, 27, 28, 29],
                visibility: 1,
                attribute_id: 26,
                type: "dropdown",
            },
            storage: {
                name: "Storage",
                position: 2,
                key: "storage",
                value: [31, 32],
                visibility: 1,
                attribute_id: 28,
                type: "dropdown",
            },
            size: {
                name: "Size",
                position: 3,
                key: "size",
                value: ["Small", "Large"],
                visibility: "1",
                attribute_id: "",
                type: "dropdown",
            },
            category: {
                name: "Category",
                position: 4,
                key: "category",
                value: ["A", "B", "C", "D"],
                visibility: "1",
                attribute_id: "",
                type: "dropdown",
            },
        },
        attribute_values: {
            color: {
                1: {
                    id: 25,
                    attribute_id: 26,
                    value: "Grey",
                    order_by: 2,
                    status: "Active",
                    created_at: "2022-06-22T06:33:07.000000Z",
                    updated_at: null,
                },
                2: {
                    id: 26,
                    attribute_id: 26,
                    value: "Pink",
                    order_by: 2,
                    status: "Active",
                    created_at: "2022-06-22T06:33:07.000000Z",
                    updated_at: null,
                },
                3: {
                    id: 27,
                    attribute_id: 26,
                    value: "Blue",
                    order_by: 2,
                    status: "Active",
                    created_at: "2022-06-22T06:33:07.000000Z",
                    updated_at: null,
                },
                4: {
                    id: 28,
                    attribute_id: 26,
                    value: "Yellow",
                    order_by: 2,
                    status: "Active",
                    created_at: "2022-06-22T06:33:07.000000Z",
                    updated_at: null,
                },
                5: {
                    id: 29,
                    attribute_id: 26,
                    value: "Green",
                    order_by: 2,
                    status: "Active",
                    created_at: "2022-06-22T06:33:07.000000Z",
                    updated_at: null,
                },
            },
            storage: {
                7: {
                    id: 31,
                    attribute_id: 28,
                    value: "32 GB",
                    order_by: 1,
                    status: "Active",
                    created_at: "2022-06-22T06:33:07.000000Z",
                    updated_at: null,
                },
                8: {
                    id: 32,
                    attribute_id: 28,
                    value: "64 GB",
                    order_by: 2,
                    status: "Active",
                    created_at: "2022-06-22T06:33:07.000000Z",
                    updated_at: null,
                },
            },
        },
        variations: [
            {
                id: 1079,
                code: "",
                sku: null,
                parent_id: 1080,
                regular_price: "$89.000",
                sale_price: "$79.000",
                available_from: null,
                available_to: null,
                summary: null,
                created_at: "22-06-2022 02:33 PM",
                attributes: {
                    attribute_flavor: "Banana",
                    attribute_color: 27,
                    attribute_storage: 32,
                    attribute_size: "Large",
                    attribute_category: "B",
                },
                images: ["http://multivendor.com/images/image2.jpg"],
            },
            {
                id: 1080,
                code: "",
                sku: null,
                parent_id: 1080,
                regular_price: "$89.000",
                sale_price: "$79.000",
                available_from: null,
                available_to: null,
                summary: null,
                created_at: "22-06-2022 02:33 PM",
                attributes: {
                    attribute_flavor: "Chocolate",
                    attribute_color: 25,
                    attribute_storage: 31,
                    attribute_size: "Large",
                    attribute_category: "D",
                },
                images: ["http://multivendor.com/images/image2.jpg"],
            },
            {
                id: 1081,
                code: "",
                sku: null,
                parent_id: 1080,
                regular_price: "$89.000",
                sale_price: "$79.000",
                available_from: null,
                available_to: null,
                summary: null,
                created_at: "22-06-2022 02:33 PM",
                attributes: {
                    attribute_flavor: "Vanilla",
                    attribute_color: 26,
                    attribute_storage: 32,
                    attribute_size: "Small",
                    attribute_category: "A",
                },
                images: ["http://multivendor.com/images/image2.jpg"],
            },
            {
                id: 1082,
                code: "",
                sku: null,
                parent_id: 1080,
                regular_price: "$70.000",
                sale_price: "$50.000",
                available_from: null,
                available_to: null,
                summary: null,
                created_at: "22-06-2022 02:33 PM",
                attributes: {
                    attribute_flavor: "Banana",
                    attribute_color: 25,
                    attribute_storage: 32,
                    attribute_size: "Small",
                    attribute_category: "C",
                },
                images: ["http://multivendor.com/images/image2.jpg"],
            },
            {
                id: 1083,
                code: "",
                sku: null,
                parent_id: 1080,
                regular_price: "$45.000",
                sale_price: "$38.000",
                available_from: null,
                available_to: null,
                summary: null,
                created_at: "22-06-2022 02:33 PM",
                attributes: {
                    attribute_flavor: "Vanilla",
                    attribute_color: 25,
                    attribute_storage: 31,
                    attribute_size: "Small",
                    attribute_category: "B",
                },
                images: ["http://multivendor.com/images/image2.jpg"],
            },
            {
                id: 1084,
                code: "",
                sku: null,
                parent_id: 1080,
                regular_price: "$99.000",
                sale_price: "$89.000",
                available_from: null,
                available_to: null,
                summary: null,
                created_at: "22-06-2022 02:33 PM",
                attributes: {
                    attribute_flavor: "Vanilla",
                    attribute_color: 28,
                    attribute_storage: 31,
                    attribute_size: "Small",
                    attribute_category: "D",
                },
                images: ["http://multivendor.com/images/image2.jpg"],
            },
            {
                id: 1085,
                code: "",
                sku: null,
                parent_id: 1080,
                regular_price: "$52.000",
                sale_price: "$45.000",
                available_from: null,
                available_to: null,
                summary: null,
                created_at: "22-06-2022 02:33 PM",
                attributes: {
                    attribute_flavor: "Vanilla",
                    attribute_color: 27,
                    attribute_storage: 32,
                    attribute_size: "Large",
                    attribute_category: "B",
                },
                images: ["http://multivendor.com/images/image2.jpg"],
            },
            {
                id: 1086,
                code: "",
                sku: null,
                parent_id: 1080,
                regular_price: "$78.000",
                sale_price: "$70.000",
                available_from: null,
                available_to: null,
                summary: null,
                created_at: "22-06-2022 02:33 PM",
                attributes: {
                    attribute_flavor: "Banana",
                    attribute_color: 27,
                    attribute_storage: 31,
                    attribute_size: "Small",
                    attribute_category: "C",
                },
                images: ["http://multivendor.com/images/image2.jpg"],
            },
            {
                id: 1087,
                code: "",
                sku: null,
                parent_id: 1080,
                regular_price: "$85.000",
                sale_price: "$76.000",
                available_from: null,
                available_to: null,
                summary: null,
                created_at: "22-06-2022 02:33 PM",
                attributes: {
                    attribute_flavor: "Vanilla",
                    attribute_color: 27,
                    attribute_storage: 31,
                    attribute_size: "Small",
                    attribute_category: "B",
                },
                images: ["http://multivendor.com/images/image2.jpg"],
            },
            {
                id: 1088,
                code: "",
                sku: null,
                parent_id: 1080,
                regular_price: "$80.000",
                sale_price: "$70.000",
                available_from: null,
                available_to: null,
                summary: null,
                created_at: "22-06-2022 02:33 PM",
                attributes: {
                    attribute_flavor: "Vanilla",
                    attribute_color: 29,
                    attribute_storage: 31,
                    attribute_size: "Large",
                    attribute_category: "A",
                },
                images: ["http://multivendor.com/images/image2.jpg"],
            },
        ],
    },
};
